# Generated by Django 2.0.3 on 2018-03-19 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180318_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 0, 10, 15, 797826, tzinfo=utc)),
        ),
    ]
