# Generated by Django 2.0.3 on 2018-03-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_auto_20180319_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('starttime', models.DateField()),
                ('now_in_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ClassProfile')),
            ],
        ),
    ]
