# Generated by Django 2.0.3 on 2018-03-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180319_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='now_in_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nowinschool', to='base.ClassProfile'),
        ),
    ]
