# Generated by Django 2.0.3 on 2018-03-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180320_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='now_in_class',
            field=models.ForeignKey(on_delete=False, related_name='nowinschool', to='base.ClassProfile'),
        ),
    ]
