# Generated by Django 2.0.3 on 2018-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180321_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classname', models.CharField(max_length=2)),
                ('chinese', models.DecimalField(decimal_places=0, max_digits=160)),
                ('math', models.DecimalField(decimal_places=0, max_digits=160)),
                ('english', models.DecimalField(decimal_places=0, max_digits=120)),
            ],
        ),
    ]
