# Generated by Django 2.0.3 on 2018-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='chinese',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='score',
            name='english',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='score',
            name='math',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
