# Generated by Django 2.0.3 on 2018-03-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180327_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='sum',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
