# Generated by Django 2.0.3 on 2018-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180327_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='chinese',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='english',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='math',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='sum',
            field=models.FloatField(default=0, null=True),
        ),
    ]
