# Generated by Django 2.0.3 on 2018-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180318_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolyearname', models.CharField(choices=[('11-12', '2011-12学年度'), ('12-13', '2012-13学年度'), ('13-14', '2013-14学年度'), ('14-15', '2014-15学年度'), ('15-16', '2015-16学年度'), ('16-17', '2016-17学年度'), ('17-18', '2017-18学年度'), ('18-19', '2018-19学年度'), ('19-20', '2019-20学年度'), ('20-21', '2020-21学年度'), ('21-22', '2021-22学年度'), ('22-23', '2022-23学年度'), ('23-24', '2023-24学年度')], max_length=8)),
                ('is_in_year', models.BooleanField(default=False)),
                ('term', models.CharField(choices=[('1', '上学期'), ('2', '下学期')], default='1', max_length=1)),
                ('starttime', models.DateField(blank=True)),
                ('endtime', models.DateField(blank=True)),
            ],
        ),
    ]
