# Generated by Django 2.0.3 on 2018-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_schoolterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolterm',
            name='endtime',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='is_in_year',
            field=models.BooleanField(default=False, verbose_name='是否当前学期'),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='schoolyearname',
            field=models.CharField(choices=[('11-12', '2011-12学年度'), ('12-13', '2012-13学年度'), ('13-14', '2013-14学年度'), ('14-15', '2014-15学年度'), ('15-16', '2015-16学年度'), ('16-17', '2016-17学年度'), ('17-18', '2017-18学年度'), ('18-19', '2018-19学年度'), ('19-20', '2019-20学年度'), ('20-21', '2020-21学年度'), ('21-22', '2021-22学年度'), ('22-23', '2022-23学年度'), ('23-24', '2023-24学年度')], max_length=8, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='starttime',
            field=models.DateField(blank=True, null=True, verbose_name='开学时间'),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='term',
            field=models.CharField(choices=[('1', '上学期'), ('2', '下学期')], default='1', max_length=1, verbose_name='学期'),
        ),
    ]
