# Generated by Django 2.0.3 on 2018-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180318_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(choices=[('高一', (('11', '高一1'), ('12', '高一2'), ('13', '高一3'), ('14', '高一4'), ('15', '高一5'), ('16', '高一6'), ('17', '高一7'), ('18', '高一8'), ('19', '高一9'))), ('高二', (('21', '高二1'), ('22', '高二2'), ('23', '高二3'), ('24', '高二4'), ('25', '高二5'), ('26', '高二6'), ('27', '高二7'), ('28', '高二8'), ('29', '高二9'))), ('高三', (('31', '高三1'), ('32', '高三2'), ('33', '高三3'), ('34', '高三4'), ('35', '高三5'), ('36', '高三6'), ('37', '高三7'), ('38', '高三8'), ('39', '高三9')))], max_length=3)),
                ('classtype', models.CharField(choices=[('高一', (('11', '高一1'), ('12', '高一2'), ('13', '高一3'), ('14', '高一4'), ('15', '高一5'), ('16', '高一6'), ('17', '高一7'), ('18', '高一8'), ('19', '高一9'))), ('高二', (('21', '高二1'), ('22', '高二2'), ('23', '高二3'), ('24', '高二4'), ('25', '高二5'), ('26', '高二6'), ('27', '高二7'), ('28', '高二8'), ('29', '高二9'))), ('高三', (('31', '高三1'), ('32', '高三2'), ('33', '高三3'), ('34', '高三4'), ('35', '高三5'), ('36', '高三6'), ('37', '高三7'), ('38', '高三8'), ('39', '高三9')))], max_length=2)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('schooltern', models.ForeignKey(on_delete=False, to='base.SchoolTerm')),
            ],
        ),
    ]
