# Generated by Django 2.0.3 on 2018-03-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_classprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classprofile',
            old_name='schooltern',
            new_name='schoolterm',
        ),
    ]
