# Generated by Django 2.0.3 on 2018-03-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180318_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classprofile',
            name='classtype',
            field=models.CharField(choices=[('00', '普通班'), ('12', '物化班'), ('13', '物生班'), ('16', '物地班'), ('15', '物政班'), ('45', '史政班'), ('56', '史地班'), ('09', '艺术班'), ('99', '综合高中班'), ('11', '其他')], max_length=2),
        ),
    ]
