# Generated by Django 2.0.3 on 2018-03-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180319_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtypename', models.CharField(choices=[('周练', '周练'), ('作业', '作业'), ('练习', '练习'), ('校统考', '校统考'), ('市统考', '市统考')], max_length=30, unique=True)),
            ],
        ),
    ]
